using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Microsoft.Extensions.Logging;

namespace AegisPC.Service.Network
{
    public enum SinkholeIpMode
    {
        Loopback,   // 127.0.0.1
        ZeroIp,     // 0.0.0.0 (Hızlı düşürme, TCP RST beklemez)
        Both        // Hem 127.0.0.1 hem 0.0.0.0
    }

    /// <summary>
    /// Windows hosts dosyasına (%WINDIR%\System32\drivers\etc\hosts) izole,
    /// güvenli ve atomik zararlı alan adı sinkhole enjeksiyonu yapan yardımcı sınıf.
    /// </summary>
    public class HostsInjectionHelper
    {
        private readonly ILogger<HostsInjectionHelper>? _logger;
        private readonly string _hostsFilePath;
        private readonly string _backupFilePath;
        private readonly object _fileLock = new();

        public const string SinkholeMarkerBegin = "# === AEGISPC OFFLINE DNS SINKHOLE BEGIN ===";
        public const string SinkholeMarkerEnd = "# === AEGISPC OFFLINE DNS SINKHOLE END ===";

        public string HostsFilePath => _hostsFilePath;
        public string BackupFilePath => _backupFilePath;

        public HostsInjectionHelper(string? customHostsPath = null, ILogger<HostsInjectionHelper>? logger = null)
        {
            _logger = logger;

            if (!string.IsNullOrWhiteSpace(customHostsPath))
            {
                _hostsFilePath = customHostsPath;
            }
            else
            {
                string systemDir = Environment.GetFolderPath(Environment.SpecialFolder.System);
                _hostsFilePath = Path.Combine(systemDir, "drivers", "etc", "hosts");
            }

            _backupFilePath = _hostsFilePath + ".aegispc.bak";
        }

        /// <summary>
        /// Zararlı alan adlarını kategori bazlı olarak hosts dosyasına enjekte eder.
        /// </summary>
        public bool ApplySinkhole(
            IEnumerable<(string Domain, string Category)> domainEntries,
            SinkholeIpMode ipMode = SinkholeIpMode.Loopback)
        {
            if (domainEntries == null) return false;

            lock (_fileLock)
            {
                try
                {
                    if (!File.Exists(_hostsFilePath))
                    {
                        var dir = Path.GetDirectoryName(_hostsFilePath);
                        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                        {
                            Directory.CreateDirectory(dir);
                        }
                        File.WriteAllText(_hostsFilePath, "# Localhost default hosts file\r\n127.0.0.1 localhost\r\n::1 localhost\r\n");
                    }

                    // 1. Temiz Yedek Alma (Daha önce alınmadıysa orijinali sakla)
                    EnsureCleanBackupExists();

                    // 2. Mevcut içeriği oku ve eski sinkhole bloğunu çıkar
                    string existingContent = File.ReadAllText(_hostsFilePath);
                    string cleanedContent = StripSinkholeBlock(existingContent);

                    // 3. Yeni sinkhole bloğunu inşa et
                    var sb = new StringBuilder();
                    sb.Append(cleanedContent.TrimEnd());
                    sb.AppendLine();
                    sb.AppendLine();
                    sb.AppendLine(SinkholeMarkerBegin);
                    sb.AppendLine($"# Generated by AegisPC Ultron Defender at: {DateTime.UtcNow:u}");
                    sb.AppendLine("# Automatically sinkholing Phishing, Malvertising, C2, and Crypto Mining domains.");

                    var grouped = domainEntries
                        .Where(e => !string.IsNullOrWhiteSpace(e.Domain))
                        .GroupBy(e => e.Category ?? "General", StringComparer.OrdinalIgnoreCase);

                    int totalCount = 0;
                    foreach (var group in grouped)
                    {
                        sb.AppendLine();
                        sb.AppendLine($"# --- Category: {group.Key} ---");

                        foreach (var (rawDomain, _) in group)
                        {
                            string domain = CleanDomain(rawDomain);
                            if (string.IsNullOrEmpty(domain)) continue;

                            switch (ipMode)
                            {
                                case SinkholeIpMode.Loopback:
                                    sb.AppendLine($"127.0.0.1 {domain}");
                                    break;
                                case SinkholeIpMode.ZeroIp:
                                    sb.AppendLine($"0.0.0.0 {domain}");
                                    break;
                                case SinkholeIpMode.Both:
                                    sb.AppendLine($"127.0.0.1 {domain}");
                                    sb.AppendLine($"0.0.0.0 {domain}");
                                    break;
                            }
                            totalCount++;
                        }
                    }

                    sb.AppendLine();
                    sb.AppendLine(SinkholeMarkerEnd);

                    // 4. Atomik Dosya Yazma (Önce .tmp yaz, sonra replace/overwrite)
                    AtomicWriteFile(_hostsFilePath, sb.ToString());

                    // 5. DNS Çözümleyici Önbelleğini Temizle
                    FlushDnsCache();

                    _logger?.LogInformation("Hosts sinkhole başarıyla güncellendi ({Count} alan adı enjekte edildi).", totalCount);
                    return true;
                }
                catch (Exception ex)
                {
                    _logger?.LogError(ex, "Hosts dosyası güncellenirken hata oluştu: {File}", _hostsFilePath);
                    return false;
                }
            }
        }

        /// <summary>
        /// Hosts dosyasındaki AegisPC sinkhole bloğunu tamamen kaldırır.
        /// </summary>
        public bool RemoveSinkhole()
        {
            lock (_fileLock)
            {
                try
                {
                    if (!File.Exists(_hostsFilePath)) return true;

                    string existingContent = File.ReadAllText(_hostsFilePath);
                    if (!existingContent.Contains(SinkholeMarkerBegin))
                    {
                        return true; // Zaten enjeksiyon yok
                    }

                    string cleanedContent = StripSinkholeBlock(existingContent);
                    AtomicWriteFile(_hostsFilePath, cleanedContent);

                    FlushDnsCache();
                    _logger?.LogInformation("Hosts dosyasından AegisPC sinkhole bloğu temizlendi.");
                    return true;
                }
                catch (Exception ex)
                {
                    _logger?.LogError(ex, "Hosts dosyasından sinkhole kaldırılırken hata oluştu.");
                    return false;
                }
            }
        }

        /// <summary>
        /// Orijinal yedek dosyasından hosts dosyasını geri yükler.
        /// </summary>
        public bool RestoreBackup()
        {
            lock (_fileLock)
            {
                try
                {
                    if (!File.Exists(_backupFilePath))
                    {
                        _logger?.LogWarning("Yedek dosyası bulunamadı: {Backup}", _backupFilePath);
                        return false;
                    }

                    File.Copy(_backupFilePath, _hostsFilePath, overwrite: true);
                    FlushDnsCache();
                    _logger?.LogInformation("Hosts dosyası orijinal yedeğinden başarıyla geri yüklendi.");
                    return true;
                }
                catch (Exception ex)
                {
                    _logger?.LogError(ex, "Hosts dosyası yedekten geri yüklenemedi.");
                    return false;
                }
            }
        }

        /// <summary>
        /// Hosts dosyasında aktif bir AegisPC sinkhole bloğu olup olmadığını kontrol eder.
        /// </summary>
        public bool IsSinkholeActive()
        {
            try
            {
                if (!File.Exists(_hostsFilePath)) return false;
                string content = File.ReadAllText(_hostsFilePath);
                return content.Contains(SinkholeMarkerBegin) && content.Contains(SinkholeMarkerEnd);
            }
            catch
            {
                return false;
            }
        }

        /// <summary>
        /// Sinkhole bloğunda engellenen aktif kayıt sayısını döndürür.
        /// </summary>
        public int GetSinkholeEntryCount()
        {
            try
            {
                if (!File.Exists(_hostsFilePath)) return 0;
                var lines = File.ReadAllLines(_hostsFilePath);

                bool insideBlock = false;
                int count = 0;

                foreach (var line in lines)
                {
                    var trimmed = line.Trim();
                    if (trimmed == SinkholeMarkerBegin)
                    {
                        insideBlock = true;
                        continue;
                    }
                    if (trimmed == SinkholeMarkerEnd)
                    {
                        insideBlock = false;
                        break;
                    }

                    if (insideBlock && !trimmed.StartsWith("#") && !string.IsNullOrWhiteSpace(trimmed))
                    {
                        count++;
                    }
                }

                return count;
            }
            catch
            {
                return 0;
            }
        }

        private void EnsureCleanBackupExists()
        {
            try
            {
                if (!File.Exists(_backupFilePath) && File.Exists(_hostsFilePath))
                {
                    string existing = File.ReadAllText(_hostsFilePath);
                    // Eğer mevcut dosyada zaten sinkhole varsa onu temizleyip yedekle
                    string clean = StripSinkholeBlock(existing);
                    File.WriteAllText(_backupFilePath, clean);
                    _logger?.LogInformation("Orijinal hosts dosyası yedeklendi: {Backup}", _backupFilePath);
                }
            }
            catch (Exception ex)
            {
                _logger?.LogWarning(ex, "Hosts dosyası yedeklenirken uyarı.");
            }
        }

        public static string StripSinkholeBlock(string content)
        {
            if (string.IsNullOrEmpty(content)) return string.Empty;

            int startIndex = content.IndexOf(SinkholeMarkerBegin, StringComparison.Ordinal);
            if (startIndex >= 0)
            {
                int endIndex = content.IndexOf(SinkholeMarkerEnd, startIndex, StringComparison.Ordinal);
                if (endIndex >= 0)
                {
                    int totalLength = (endIndex + SinkholeMarkerEnd.Length) - startIndex;
                    return content.Remove(startIndex, totalLength).TrimEnd();
                }
            }
            return content.TrimEnd();
        }

        private static void AtomicWriteFile(string targetPath, string content)
        {
            string dir = Path.GetDirectoryName(targetPath) ?? ".";
            string tempFile = Path.Combine(dir, $"hosts_tmp_{Guid.NewGuid():N}.tmp");

            try
            {
                File.WriteAllText(tempFile, content, Encoding.UTF8);

                // Dosya özniteliklerini kontrol et (Read-only ise kaldır)
                if (File.Exists(targetPath))
                {
                    var attr = File.GetAttributes(targetPath);
                    if (attr.HasFlag(FileAttributes.ReadOnly))
                    {
                        File.SetAttributes(targetPath, attr & ~FileAttributes.ReadOnly);
                    }
                }

                File.Move(tempFile, targetPath, overwrite: true);
            }
            finally
            {
                if (File.Exists(tempFile))
                {
                    try { File.Delete(tempFile); } catch { }
                }
            }
        }

        private static string CleanDomain(string domain)
        {
            if (string.IsNullOrWhiteSpace(domain)) return string.Empty;
            string clean = domain.Trim().ToLowerInvariant();

            // Scheme veya path varsa ayıkla
            if (clean.StartsWith("http://") || clean.StartsWith("https://"))
            {
                if (Uri.TryCreate(clean, UriKind.Absolute, out var uri))
                {
                    clean = uri.Host;
                }
            }

            clean = clean.Split('/')[0].Split(':')[0].Trim();
            return clean.TrimStart('.');
        }

        [DllImport("dnsapi.dll", EntryPoint = "DnsFlushResolverCache", SetLastError = true)]
        private static extern int DnsFlushResolverCache();

        public static void FlushDnsCache()
        {
            try
            {
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    DnsFlushResolverCache();
                }
            }
            catch { }

            try
            {
                using var proc = Process.Start(new ProcessStartInfo
                {
                    FileName = "ipconfig.exe",
                    Arguments = "/flushdns",
                    CreateNoWindow = true,
                    UseShellExecute = false
                });
                proc?.WaitForExit(2000);
            }
            catch { }
        }
    }
}
