<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AegisPC.Core</RootNamespace>
    <AssemblyName>AegisPC.Core</AssemblyName>
  </PropertyGroup>
</Project>
