<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AegisPC.Contracts</RootNamespace>
    <AssemblyName>AegisPC.Contracts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AegisPC.Core\AegisPC.Core.csproj" />
  </ItemGroup>
</Project>
