<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AegisPC.Uninstaller</RootNamespace>
    <AssemblyName>Uninstall</AssemblyName>
    <Product>Ultron Defender Total Security</Product>
    <Company>Ultron Security Technologies</Company>
    <ApplicationIcon>Resources\Images\ultron_shield.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
</Project>